larger initrd, can be stipped down later when everything works
several typos fixed

disabled keymaps on s390

diff --git a/scripts/mk-images b/scripts/mk-images
--- a/scripts/mk-images
+++ b/scripts/mk-images
@@ -94,11 +94,14 @@ TOPDIR=$(cd $TOPDIR; pwd)
 
     if [ -n "$dieLater" ]; then exit 1; fi
 
-    # go ahead and create the keymaps so we only have to do it once
-    $GETKEYMAPS $BUILDARCH $KEYMAPS $IMGPATH
-    if [ $? != 0 ]; then
-        echo "Unable to create keymaps and thus can't create initrd."
-	exit 1
+    if [ "$BUILDARCH" != "s390" -a "$BUILDARCH" != "s390x" ]; then
+       # go ahead and create the keymaps so we only have to do it once
+       echo "GETKEYMAPS: $GETKEYMAPS : $BUILDARCH : $KEYMAPS : $IMGPATH"
+       $GETKEYMAPS $BUILDARCH $KEYMAPS $IMGPATH
+       if [ $? != 0 ]; then
+           echo "Unable to create keymaps and thus can't create initrd."
+	   exit 1
+       fi
     fi
  
 findPackage() {
@@ -412,7 +415,9 @@ EOF
 
     install -s -m 755 $LOADERBINDIR/$LOADERBIN $MBD_DIR/sbin/loader
     install -s -m 755 $LOADERBINDIR/$INITBIN $MBD_DIR/sbin
-    install -m 644 $KEYMAPS $MBD_DIR/etc/keymaps.gz
+    if [ "$BUILDARCH" != "s390" -a "$BUILDARCH" != "s390x" ]; then
+       install -m 644 $KEYMAPS $MBD_DIR/etc/keymaps.gz
+    fi
     install -m 644 $FONTS $MBD_DIR/etc/fonts.cgz
     install -m 644 $MYLANGTABLE $MBD_DIR/etc/lang-table
     
@@ -495,7 +500,7 @@ EOF
     ln -s fb0 $MBD_DIR/dev/fb
 
     dd if=/dev/zero of=$MBD_DIR/etc/ramfs.img.big bs=1k count=16000
-    mke2fs -Fq $MBD_DIR/etc/ramfs.img.big
+    mke2fs -F -q $MBD_DIR/etc/ramfs.img.big
     gzip -9 < $MBD_DIR/etc/ramfs.img.big > $MBD_DIR/etc/ramfs.img
     rm -f $MBD_DIR/etc/ramfs.img.big
 
@@ -506,7 +511,7 @@ EOF
 
     rm -f $MBD_FSIMAGE
     dd if=/dev/zero of=$MBD_FSIMAGE bs=1k count=$INITRDSIZE 2> /dev/null
-    echo y | /sbin/mke2fs -i 1024 -q $MBD_FSIMAGE $INITRDSIZE > /dev/null 2>/dev/null
+    /sbin/mke2fs -F -i 1024 -q $MBD_FSIMAGE $INITRDSIZE > /dev/null 2>/dev/null
 
     rm -rf $MBD_MNTPOINT
     mkdir $MBD_MNTPOINT
@@ -621,7 +626,7 @@ makeImage () {
     mkdir -p $MI_MNTPOINT
 
     dd if=/dev/zero of=$MI_TMPIMAGE bs=1k count=$MI_SIZE 2>/dev/null
-    echo y | /sbin/mke2fs -i 4096 $MI_TMPIMAGE  > /dev/null 2>/dev/null
+    /sbin/mke2fs -F -i 4096 $MI_TMPIMAGE  > /dev/null 2>/dev/null
     mount -o loop $MI_TMPIMAGE $MI_MNTPOINT
     (cd $MI_FROM; find . | cpio --quiet -p $MI_MNTPOINT)
 
@@ -692,7 +697,7 @@ makemainimage () {
 	    SIZE=$(expr $SIZE - $ERROR)
         fi
         dd if=/dev/zero bs=1k count=${SIZE} of=$mmi_tmpimage
-        echo y | mke2fs $mmi_tmpimage > /dev/null 
+        mke2fs -F $mmi_tmpimage > /dev/null 
         mount -o loop $mmi_tmpimage $mmi_mntpoint
 
         (cd $IMGPATH; find . | fgrep -v "./usr/lib/anaconda-runtime" |
@@ -746,7 +751,7 @@ makedriverdisk () {
     fi
 
     dd if=/dev/zero of=/tmp/$diskname.img bs=1k count=$size 2> /dev/null
-    echo y | /sbin/mke2fs -i 4096 /tmp/$diskname.img  > /dev/null 2>/dev/null
+    /sbin/mke2fs -F -i 4096 /tmp/$diskname.img  > /dev/null 2>/dev/null
     mkdir -p /tmp/mkdd.$$
     mount -t ext2 -o loop /tmp/$diskname.img /tmp/mkdd.$$
     rmdir /tmp/mkdd.$$/lost+found
@@ -794,6 +799,7 @@ for kernelvers in $vertag; do
 	echo 'kernel-$kernelvers does not exist -- using kernel package'
 	kpackage=$($LATEST $KERNELPATH kernel)
 	vertag=""
+	kernelvers=""
     fi
 
     ppackage=$($LATEST $KERNELPATH kernel-pcmcia-cs)
@@ -801,7 +807,7 @@ for kernelvers in $vertag; do
 	ppackage=""
     fi
 
-    version=$(rpm --qf '%{VERSION}-%{RELEASE}' -qp $kpackage)${vertag}
+    version=$(rpm --qf '%{VERSION}-%{RELEASE}' -qp $kpackage)${kernelvers}
     echo "unpacking $kpackage"
 
     rpm2cpio $kpackage | (cd $KERNELROOT; cpio --quiet -iumd)
